services:
  postgres:
    image: postgres:latest
    container_name: postgres_api_turmas
    restart: always
    environment:
      POSTGRES_DB: apiTurmas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge
